# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vision_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vision_service.proto\x12\x0evision_service\"\xae\x01\n\x0f\x44\x65tectionResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nskill_name\x18\x02 \x01(\t\x12-\n\ndetections\x18\x03 \x03(\x0b\x32\x19.vision_service.Detection\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\x11\n\tvideo_url\x18\x05 \x01(\t\x12\x13\n\x0b\x61lert_level\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\"\xd0\x01\n\tDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12)\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x1b.vision_service.BoundingBox\x12=\n\nattributes\x18\x04 \x03(\x0b\x32).vision_service.Detection.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"a\n\x15ImageDetectionRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\nskill_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61lert_level\x18\x03 \x01(\t\x12\x0b\n\x03roi\x18\x04 \x03(\t\"\x88\x01\n\x12VideoStreamRequest\x12\x12\n\nstream_url\x18\x01 \x01(\t\x12\x12\n\nskill_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61lert_level\x18\x03 \x01(\t\x12\x16\n\x0e\x66rame_interval\x18\x04 \x01(\x05\x12\x0b\n\x03roi\x18\x05 \x03(\t\x12\x10\n\x08schedule\x18\x06 \x01(\t\"H\n\x11\x44\x65tectionResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xc8\x01\n\rVisionService\x12Y\n\x0b\x44\x65tectImage\x12%.vision_service.ImageDetectionRequest\x1a!.vision_service.DetectionResponse\"\x00\x12\\\n\x11\x44\x65tectVideoStream\x12\".vision_service.VideoStreamRequest\x1a!.vision_service.DetectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTION_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_DETECTION_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_DETECTIONRESULT']._serialized_start=41
  _globals['_DETECTIONRESULT']._serialized_end=215
  _globals['_DETECTION']._serialized_start=218
  _globals['_DETECTION']._serialized_end=426
  _globals['_DETECTION_ATTRIBUTESENTRY']._serialized_start=377
  _globals['_DETECTION_ATTRIBUTESENTRY']._serialized_end=426
  _globals['_BOUNDINGBOX']._serialized_start=428
  _globals['_BOUNDINGBOX']._serialized_end=494
  _globals['_IMAGEDETECTIONREQUEST']._serialized_start=496
  _globals['_IMAGEDETECTIONREQUEST']._serialized_end=593
  _globals['_VIDEOSTREAMREQUEST']._serialized_start=596
  _globals['_VIDEOSTREAMREQUEST']._serialized_end=732
  _globals['_DETECTIONRESPONSE']._serialized_start=734
  _globals['_DETECTIONRESPONSE']._serialized_end=806
  _globals['_VISIONSERVICE']._serialized_start=809
  _globals['_VISIONSERVICE']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
