# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vision_service_pb2 as vision__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vision_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionServiceStub(object):
    """视觉AI服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectImage = channel.unary_unary(
                '/vision_service.VisionService/DetectImage',
                request_serializer=vision__service__pb2.ImageDetectionRequest.SerializeToString,
                response_deserializer=vision__service__pb2.DetectionResponse.FromString,
                _registered_method=True)
        self.DetectVideoStream = channel.unary_unary(
                '/vision_service.VisionService/DetectVideoStream',
                request_serializer=vision__service__pb2.VideoStreamRequest.SerializeToString,
                response_deserializer=vision__service__pb2.DetectionResponse.FromString,
                _registered_method=True)


class VisionServiceServicer(object):
    """视觉AI服务
    """

    def DetectImage(self, request, context):
        """图片检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectVideoStream(self, request, context):
        """视频流检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectImage,
                    request_deserializer=vision__service__pb2.ImageDetectionRequest.FromString,
                    response_serializer=vision__service__pb2.DetectionResponse.SerializeToString,
            ),
            'DetectVideoStream': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectVideoStream,
                    request_deserializer=vision__service__pb2.VideoStreamRequest.FromString,
                    response_serializer=vision__service__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision_service.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vision_service.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService(object):
    """视觉AI服务
    """

    @staticmethod
    def DetectImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision_service.VisionService/DetectImage',
            vision__service__pb2.ImageDetectionRequest.SerializeToString,
            vision__service__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectVideoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision_service.VisionService/DetectVideoStream',
            vision__service__pb2.VideoStreamRequest.SerializeToString,
            vision__service__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
